name: Publish Package to npmjs

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
    #  contents: read
    #  id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://a99f-221-255-180-194.ngrok-free.app'
      #- run: npm ci
      #- run: npm publish --provenance --access public
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
